apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
resources:
  - ../../base
  - namespace.yaml

images:
  - name: repo-app
    newName: 809123645552.dkr.ecr.us-east-1.amazonaws.com/default/repo-app
    newTag: ba11f1af777321b154d8f5ae391703dce922f4b9

patches:
  - target:
      kind: Deployment
      name: my-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
